FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# SeedDMS

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/documents]

### List All Documents [GET]

+ Response 200 (application/json)

        [
            {
                {"document":"0001"},
                {"document":"0002"}
            }
        ]

