FORMAT: 1A
HOST: https://seeddms.apiblueprint.org/

# SeedDMS

SeedDMS is a simple API in which users can get/add documents.

## Questions Collection [/documents]

### List All Documents [GET]

+ Response 200 (application/json)

        [
            {
                {"document":"0001"},
                {"document":"0002"}
            }
        ]

